[INJIMOB-843]: enhance text in otp verification
mosip/inji pull request #1315
Opened 2024-02-29 14:09 UTC by srikanth716

![Screenshot_1709214068](https://github.com/mosip/inji/assets/97477121/491bbb2c-d864-4419-b1af-5da19d48e8c9)

2024-03-05 09:07 UTC, Alka1703 requested changes

2024-03-05 09:29 UTC, swatigoel commented on screens/Home/MyVcs/GetIdInputModal.tsx
> +  useEffect(() => {
@srikanth716 can you please check it?

2024-03-05 11:36 UTC, srikanth716 commented on screens/Home/MyVcs/GetIdInputModal.tsx
> +  useEffect(() => {
pushed to commonUtils.ts

2024-03-06 06:30 UTC, vijay151096 approved these changes
looks good to me.

2024-03-06 06:30 UTC, merged