Injimob 1204 share qr code
mosip/inji pull request #1469
Opened 2024-05-30 07:21 UTC by balachandarg-tw

## Description

> Describe the Changes in the PR
- Updating the base64 string state variable from the getRef property of QRcode which gives base64 string.
- Using react-native-share , Passing the sharing options(text and image) to the library , so that it will be shared to other supported apps installed in device.

##[ Issue ticket number and link](https://mosip.atlassian.net/jira/software/c/projects/INJIMOB/boards/91?selectedIssue=INJIMOB-1204)

## Screenshots

> Add the Screenshots of the feature.

2024-05-30 11:37 UTC, sree96 commented on components/QrCodeOverlay.tsx
> +                margin="30 0 0 0"
Move this to themes

2024-05-30 11:39 UTC, sree96 commented on locales/ara.json
> +    "share_qr_code": "مشاركة رمز الاستجابة السريعة"
We use camelcase convention

2024-05-30 11:39 UTC, sree96 commented on locales/en.json
> +    "share_qr_code": "Share QR Code"
We use camelcase convention

2024-05-30 11:39 UTC, sree96 commented on locales/fil.json
> +    "share_qr_code": "Ibahagi ang QR Code"
We use camelcase convention

2024-05-30 11:39 UTC, sree96 commented on locales/kan.json
> +    "share_qr_code": "QR ಕೋಡ್ ಹಂಚಿಕೊಳ್ಳಿ"
We use camelcase convention

2024-05-30 11:39 UTC, sree96 commented on locales/tam.json
> +    "share_qr_code": "QR குறியீட்டைப் பகிரவும்"
We use camelcase convention

2024-05-30 11:41 UTC, sree96 commented on shared/sharing/sharing-image-utils.ts
> +    console.log('Image shared suuccessfully::');
Please remove the logs

2024-05-30 11:42 UTC, sree96 requested changes
Please address the comments

2024-05-30 13:04 UTC, balachandarg-tw commented on components/QrCodeOverlay.tsx
> +                margin="30 0 0 0"
Done

2024-05-30 13:04 UTC, balachandarg-tw commented on locales/ara.json
> +    "share_qr_code": "مشاركة رمز الاستجابة السريعة"
Done

2024-05-30 13:04 UTC, balachandarg-tw commented on locales/fil.json
> +    "share_qr_code": "Ibahagi ang QR Code"
Done

2024-05-30 13:04 UTC, balachandarg-tw commented on locales/hin.json
> +    "share_qr_code": "QR कोड साझा करें"
Done

2024-05-30 13:04 UTC, balachandarg-tw commented on locales/kan.json
> +    "share_qr_code": "QR ಕೋಡ್ ಹಂಚಿಕೊಳ್ಳಿ"
Done

2024-05-30 13:04 UTC, balachandarg-tw commented on locales/tam.json
> +    "share_qr_code": "QR குறியீட்டைப் பகிரவும்"
Done

2024-05-30 13:05 UTC, balachandarg-tw commented on shared/sharing/sharing-image-utils.ts
> +    console.log('Image shared suuccessfully::');
Removed

2024-05-30 13:17 UTC, sree96 approved these changes

2024-05-31 11:58 UTC, merged

2024-06-03 04:45 UTC, swatigoel commented on components/QrCodeOverlay.tsx
> +  }, [base64String]);
@balachandarg-tw @KiruthikaJeyashankar why we need shareQRCode in useEffect. Share QRCode is manual step by end user.

2024-06-03 04:45 UTC, swatigoel commented on shared/sharing/sharing-image-utils.ts
> +import RNShare, {ShareOptions} from 'react-native-share';
Why this filename is in kebab case?