[INJIMOB-1093] draft13 changes
mosip/inji pull request #1566
Opened 2024-07-23 12:04 UTC by abhip2565

## Description

> This PR includes draft 13 changes. Major changes include:

- Change in issuer model.
- Removal of issuerconfigfetch api
- Addition of bg image property.

## Issue ticket number and link

> Example : https://mosip.atlassian.net/jira/software/c/projects/INJIMOB/boards/91?selectedIssue=INJIMOB-1093

2024-07-25 03:00 UTC, swatigoel requested changes

2024-07-25 06:29 UTC, sree96 commented on components/VC/Views/VCCardViewContent.tsx
> +      imageStyle={{opacity: 0.1}}
Can we move it to styles?

2024-07-25 06:30 UTC, sree96 commented on components/VC/Views/VCDetailView.tsx
> +              imageStyle={{width: '100%', opacity: 0.1}}
Can we move it to styles?

2024-07-25 06:33 UTC, sree96 commented on screens/Home/ViewVcModal.tsx
> +            style={{ borderRadius: 5, marginLeft: 2 }}
can we move it to styles?

2024-07-25 06:34 UTC, sree96 requested changes
Plz have a look at comments

2024-07-25 13:43 UTC, sree96 approved these changes

2024-07-25 15:57 UTC, swatigoel approved these changes

2024-07-25 15:58 UTC, swatigoel commented
Pending for integrating updated inji-vci-client library after making changes as per draft13 version of OpenId4VCI specification

2024-07-29 10:58 UTC, swatigoel approved these changes

2024-07-29 11:24 UTC, merged