Bugfix151
mosip/inji pull request #183
Opened 2022-10-28 06:50 UTC by srikanth716

2022-11-02 06:13 UTC, gsasikumar reviewed
.env is a local file. why is it even checked in. Delete this file. Update the read me with a sample .env file

2022-11-02 06:16 UTC, gsasikumar requested changes

2022-11-02 06:16 UTC, gsasikumar commented on .github/workflows/android-custom-build.yml
> -  backendServiceDefaultUrl: https://api-internal.qa4.mosip.net/residentmobileapp
why is it hard coded in the yml? it should be an input for yml. Look at this https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/ 
Work with chandra and his team if you need clarity.

2022-11-02 06:16 UTC, gsasikumar commented on .github/workflows/android-custom-build.yml
> -        default: 'https://api-internal.qa4.mosip.net/residentmobileapp'
same as earlier.

2023-08-18 10:04 UTC, srikanth716 commented
Closing this PR as the changes are already included

2023-08-18 10:04 UTC, closed without merging