bugfix#158
mosip/inji pull request #236
Opened 2022-11-09 10:56 UTC by srikanth716

2022-11-09 12:41 UTC, gsasikumar requested changes

2022-11-11 10:48 UTC, srikanth716 commented on components/ui/themes/DefaultTheme.ts
> +    width: 300,
> 

Fixed it by using react native Dimensions  to make it responsive according to the screen size

2022-11-11 11:08 UTC, gsasikumar requested changes

2022-11-11 11:08 UTC, gsasikumar commented on screens/Home/MyVcs/GetIdInputModal.tsx
> +                    width={Dimensions.get('screen').width * 0.8}
This is not the correct way. Because 20% is large in a bigger screen while its good in smaller screen.  Is there no other way to make it responsive?

2022-11-11 11:15 UTC, gsasikumar approved these changes

2022-11-11 11:16 UTC, merged