fix(INJI-337)testID for home screen and settings screen
mosip/inji pull request #805
Opened 2023-09-11 06:49 UTC by srikanth716

2023-09-11 07:05 UTC, swatigoel requested changes

2023-09-11 07:05 UTC, swatigoel commented on screens/MainLayout.tsx
> +              testID="help"
use testID function

2023-09-11 07:05 UTC, swatigoel commented on screens/MainLayout.tsx
> +              testID="settings"
same as above, use testID function

2023-09-11 07:05 UTC, swatigoel commented on screens/MainLayout.tsx
> +                testID={route.name}
same as above, use testID function

2023-09-11 07:05 UTC, swatigoel commented on screens/Settings/AboutInji.tsx
> +          <ListItem.Content testID="aboutInji">
use testID function

2023-09-11 07:05 UTC, swatigoel commented on screens/Settings/SettingScreen.tsx
> +          <ListItem.Content testID="language">
use testID function

2023-09-11 07:05 UTC, swatigoel commented on screens/Settings/SettingScreen.tsx
> +        arrowLeft={<Icon name={''} testID="closeSettings" />}
use testID function

2023-09-11 07:05 UTC, swatigoel commented on screens/Settings/SettingScreen.tsx
> +              <ListItem.Content testID="bioUnlock">
use testID function

2023-09-11 07:05 UTC, swatigoel commented on screens/Settings/SettingScreen.tsx
> +              <ListItem.Content testID="injiTourGuide">
use testID function

2023-09-11 07:05 UTC, swatigoel commented on screens/Settings/SettingScreen.tsx
> +              <ListItem.Content testID="logout">
use testID function

2023-09-11 07:06 UTC, swatigoel commented
In ReceivedCards components, none of the element has testID

2023-09-12 03:57 UTC, PoojaBabusing commented on components/LanguageSelector.tsx
> +    <View {...testIDProps('language')}>
can we add the testID for picker instead of view as we are handling the labels in picker.tsx

2023-09-12 04:03 UTC, PoojaBabusing commented on components/ui/Modal.tsx
> +                {...testIDProps(props.testID + ' close')}
replace line 79 with this {...testIDProps('close')}

2023-09-12 04:05 UTC, PoojaBabusing commented on screens/Settings/AboutInji.tsx
> +        {...testIDProps('aboutInji')}
add testID to listItem

2023-09-12 04:05 UTC, PoojaBabusing commented on screens/Settings/ReceivedCards.tsx
> +        {...testIDProps('receivedCards')}
add testID to column

2023-09-12 04:06 UTC, PoojaBabusing commented on screens/Settings/SettingScreen.tsx
> +                {...testIDProps('receiveCard')}
add testID to column

2023-09-12 04:07 UTC, PoojaBabusing commented on components/ui/Modal.tsx
> +                <Text testID={props.headerID} style={Theme.TextStyles.header}>
why do we need headerID ?

2023-09-12 04:28 UTC, srikanth716 commented on components/ui/Modal.tsx
> +                <Text testID={props.headerID} style={Theme.TextStyles.header}>
to assign ID to settings header

2023-09-12 07:31 UTC, merged

2023-09-12 07:33 UTC, PoojaBabusing commented on components/ui/Modal.tsx
> +                {...testIDProps(props.testID + ' arrow-left')}
yes we removed it and are also following camel casing